# -*- coding: utf-8 -*-
"""Update Installer Service - Windows Batch script 생성 및 실행"""

import logging
import subprocess
import tempfile
from pathlib import Path
from typing import Optional
import sys


logger = logging.getLogger(__name__)


class UpdateInstallerService:
    """Windows Batch script를 생성하고 실행하여 업데이트를 설치하는 서비스

    현재 실행 중인 exe를 새 버전으로 교체하는 Batch script를 생성합니다.
    Script는 다음 작업을 수행합니다:
    1. 프로세스 종료 대기 (2초)
    2. 이전 프로세스 강제 종료 (혹시 남아있을 경우)
    3. 파일 교체
    4. 새 앱 실행
    5. Batch script 자체 삭제

    Examples:
        >>> service = UpdateInstallerService()
        >>> new_exe = Path("D:/temp/SimpleTodo_new.exe")
        >>> current_exe = Path("D:/app/SimpleTodo.exe")
        >>> script_path = service.create_update_script(new_exe, current_exe)
        >>> if script_path:
        ...     service.execute_update(script_path)
    """

    def __init__(self):
        """UpdateInstallerService 초기화"""
        logger.info("UpdateInstallerService 초기화")

    def create_update_script(
        self,
        new_exe_path: Path,
        current_exe_path: Path
    ) -> Optional[Path]:
        """업데이트 Batch script를 생성합니다.

        Args:
            new_exe_path: 새 버전 exe 파일 경로
            current_exe_path: 현재 실행 중인 exe 파일 경로

        Returns:
            Optional[Path]: 생성된 script 경로 (실패 시 None)

        Raises:
            ValueError: 경로가 유효하지 않은 경우
        """
        # 경로 검증
        if not new_exe_path or not isinstance(new_exe_path, Path):
            raise ValueError(f"유효하지 않은 new_exe_path: {new_exe_path}")

        if not current_exe_path or not isinstance(current_exe_path, Path):
            raise ValueError(f"유효하지 않은 current_exe_path: {current_exe_path}")

        new_exe_path = Path(new_exe_path)
        current_exe_path = Path(current_exe_path)

        # 새 exe 파일 존재 확인
        if not new_exe_path.exists():
            logger.error(f"새 exe 파일이 존재하지 않습니다: {new_exe_path}")
            return None

        try:
            # Batch script 생성
            script_content = self._generate_batch_script(new_exe_path, current_exe_path)

            # 임시 파일로 저장
            with tempfile.NamedTemporaryFile(
                mode='w',
                encoding='utf-8',
                delete=False,
                suffix='.bat',
                prefix='SimpleTodo_Update_'
            ) as script_file:
                script_file.write(script_content)
                script_path = Path(script_file.name)

            logger.info(f"업데이트 script 생성 완료: {script_path}")
            return script_path

        except Exception as e:
            logger.error(f"Script 생성 중 오류: {e}", exc_info=True)
            return None

    def execute_update(self, script_path: Path) -> bool:
        """업데이트 Batch script를 실행하고 현재 앱을 종료합니다.

        Args:
            script_path: Batch script 경로

        Returns:
            bool: 성공 여부

        Note:
            이 메서드가 성공하면 현재 애플리케이션이 종료됩니다!
        """
        if not script_path or not isinstance(script_path, Path):
            logger.error(f"유효하지 않은 script_path: {script_path}")
            return False

        script_path = Path(script_path)

        if not script_path.exists():
            logger.error(f"Script 파일이 존재하지 않습니다: {script_path}")
            return False

        try:
            logger.info(f"업데이트 script 실행: {script_path}")

            # Batch script를 백그라운드에서 실행
            # CREATE_NO_WINDOW 플래그로 콘솔 창 숨김
            subprocess.Popen(
                [str(script_path)],
                shell=True,
                creationflags=subprocess.CREATE_NO_WINDOW if sys.platform == 'win32' else 0
            )

            logger.info("업데이트 script가 시작되었습니다. 애플리케이션을 종료합니다.")
            return True

        except Exception as e:
            logger.error(f"Script 실행 중 오류: {e}", exc_info=True)
            return False

    def _generate_batch_script(self, new_exe: Path, current_exe: Path) -> str:
        """Batch script 내용을 생성합니다.

        Args:
            new_exe: 새 버전 exe 파일 경로
            current_exe: 현재 exe 파일 경로

        Returns:
            str: Batch script 내용

        개선사항:
        1. 백업 후 교체 방식: 이전 exe를 먼저 백업하여 실패 시 복구 가능
        2. 프로세스 종료 확인 루프: taskkill 후 프로세스가 완전히 종료될 때까지 대기
        3. _MEI 임시 폴더 정리: PyInstaller 임시 폴더 명시적 삭제로 DLL 에러 방지
        """
        # Windows 경로로 변환 (백슬래시)
        new_exe_win = str(new_exe.absolute()).replace('/', '\\')
        current_exe_win = str(current_exe.absolute()).replace('/', '\\')
        backup_exe_win = current_exe_win.replace('.exe', '_old.exe')

        script = f'''@echo off
REM ============================================================
REM Simple ToDo Auto-Update Script (v2.6.43+)
REM Generated by UpdateInstallerService
REM
REM 개선사항:
REM 1. 백업 방식으로 안전한 파일 교체
REM 2. 프로세스 종료 대기 루프 추가
REM 3. PyInstaller _MEI 임시 폴더 정리
REM ============================================================

setlocal enabledelayedexpansion

echo [Simple ToDo Update] Starting update process (v2.6.43+)...

REM ============================================================
REM 1단계: 이전 exe 백업
REM ============================================================
echo [Simple ToDo Update] Backing up current executable...
if exist "{current_exe_win}" (
    ren "{current_exe_win}" "{Path(current_exe).name.replace('.exe', '_old.exe')}"
    if errorlevel 1 (
        echo [Simple ToDo Update] ERROR: Failed to backup old file
        pause
        exit /b 1
    )
)

REM ============================================================
REM 2단계: 프로세스 강제 종료
REM ============================================================
echo [Simple ToDo Update] Ensuring previous process is terminated...
taskkill /F /IM SimpleTodo.exe 2>nul

REM 프로세스 완전 종료 확인 (최대 10초 대기)
set PROCESS_WAIT=0
:WAIT_FOR_PROCESS
tasklist | find /I "SimpleTodo.exe" >nul
if %ERRORLEVEL% EQU 0 (
    if %PROCESS_WAIT% LSS 10 (
        timeout /t 1 /nobreak > nul
        set /a PROCESS_WAIT=!PROCESS_WAIT!+1
        goto WAIT_FOR_PROCESS
    ) else (
        echo [Simple ToDo Update] WARNING: Process still running after 10 seconds
    )
)

echo [Simple ToDo Update] Process terminated successfully

REM ============================================================
REM 3단계: PyInstaller 임시 폴더 정리
REM ============================================================
echo [Simple ToDo Update] Cleaning up PyInstaller temporary folders...
for /d %%i in ("%TEMP%\_MEI*") do (
    rmdir /S /Q "%%i" 2>nul
)

REM ============================================================
REM 4단계: 새 exe 파일 이동
REM ============================================================
echo [Simple ToDo Update] Moving new executable file...
move /Y "{new_exe_win}" "{current_exe_win}"
if errorlevel 1 (
    echo [Simple ToDo Update] ERROR: Failed to move new file
    REM 백업에서 복구
    echo [Simple ToDo Update] Restoring backup...
    ren "{backup_exe_win}" "{Path(current_exe).name}"
    pause
    exit /b 1
)

echo [Simple ToDo Update] File replacement completed successfully

REM ============================================================
REM 5단계: 새 앱 실행
REM ============================================================
echo [Simple ToDo Update] Starting updated application...
timeout /t 1 /nobreak > nul
start "" "{current_exe_win}"

REM ============================================================
REM 6단계: 이전 백업 파일 삭제
REM ============================================================
echo [Simple ToDo Update] Removing backup file...
timeout /t 2 /nobreak > nul
del /F /Q "{backup_exe_win}" 2>nul

REM Batch script 자체 삭제
echo [Simple ToDo Update] Cleaning up...
(goto) 2>nul & del "%~f0"
endlocal
'''

        return script

    def __repr__(self) -> str:
        """개발자용 문자열 표현을 반환합니다."""
        return "UpdateInstallerService()"
